//
//  ConversationRoomInteractor.swift
//  ConversationChat
//
//  Created by Raul Humberto Mantilla Assia on 10/23/18.
//  Copyright (c) 2018 Raul Mantilla. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol ConversationRoomBusinessLogic
    {
        func fetchMessages(request: ListMessages.FetchMessages.Request)
}

protocol ConversationRoomDataStore
{
    var messages: [RealmChatRoomConversation] { get set }
}

class ConversationRoomInteractor: ConversationRoomBusinessLogic, ConversationRoomDataStore
{
    var presenter: ConversationRoomPresentationLogic?
    var worker: ConversationRoomWorker?
    var messages: [RealmChatRoomConversation] = []
    
    // MARK:
    
    func fetchMessages(request: ListMessages.FetchMessages.Request)
    {
        worker = ConversationRoomWorker()
        
        worker?.fetchMessages{ (messages) in
            self.messages = messages
            let response = ListMessages.FetchMessages.Response(messages: messages)
            self.presenter?.presentMessages(response: response)
        }
    }
}
