//
//  ListContactsPresenter.swift
//  ConversationChat
//
//  Created by Raul Mantilla on 20/10/18.
//  Copyright (c) 2018 Raul Mantilla. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListContactsPresentationLogic
{
  func presentContacts(response: ListContacts.FetchContacts.Response)
  func presentCreatedChatRoom(response: ListContacts.createChatRoom.Response)
}

class ListContactsPresenter: ListContactsPresentationLogic
{
  weak var viewController: ListContactsDisplayLogic?
  
  // MARK: Do something
  
  func presentContacts(response: ListContacts.FetchContacts.Response)
  {
    var contacts: [ListContacts.FetchContacts.ViewModel.DisplayedContact] = []
    for contact in response.contacts
    {
        let displayedContacts = ListContacts.FetchContacts.ViewModel.DisplayedContact(id: contact.id, name: contact.name, lastname: contact.lastname, fullname: contact.fullname, initials: contact.initials, phoneNumber: contact.phoneNumber, avatarUrl: contact.avatarUrl, description: nil)
        
        contacts.append(displayedContacts)
    }
    let viewModel = ListContacts.FetchContacts.ViewModel(displayedContacts: contacts)
    viewController?.displayContacts(viewModel: viewModel)
  }
    
    func presentCreatedChatRoom(response: ListContacts.createChatRoom.Response){
        viewController?.createdChatRoom()
    }
    /*
    func presentChatRoom(response: ListContacts.createChatRoom.Response)
    {
        var chatRom: [DisplayedContact] = []
        for contact in response.contacts
        {
            let displayedContacts = DisplayedContact(id: contact.id, name: contact.name, lastname: contact.lastname, fullname: contact.fullname, initials: contact.initials, phoneNumber: contact.phoneNumber, avatarUrl: contact.avatarUrl, description: nil, hashValue: 0)
            
            contacts.append(displayedContacts)
        }
        let viewModel = ListContacts.FetchContacts.ViewModel(displayedContacts: contacts)
        viewController?.displayContacts(viewModel: viewModel)
    }
    self.presenter?.presentChatRoom(response: response)
 */
}
