//
//  ListContactsRouter.swift
//  ConversationChat
//
//  Created by Raul Mantilla on 20/10/18.
//  Copyright (c) 2018 Raul Mantilla. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListContactsRoutingLogic
{
    func routeToConversation()
}

protocol ListContactsDataPassing
{
    var dataStore: ListContactsDataStore? { get set }
}

class ListContactsRouter: NSObject, ListContactsRoutingLogic, ListContactsDataPassing
{
    weak var viewController: ListContactsViewController?
    var dataStore: ListContactsDataStore?
    
    // MARK: Routing
    
    func routeToConversation()
    {   
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "ConversationRoomViewController") as! ConversationRoomViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToConversation(source: dataStore!, destination: &destinationDS)
        navigateToConversation(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToConversation(source: ListContactsViewController, destination: ConversationRoomViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToConversation(source: ListContactsDataStore, destination: inout ConversationRoomDataStore)
    {
        if let chatRoom = source.createdChatRoom {
            destination.chatRoom = chatRoom
        }
    }
}
