//
//  ListContactsInteractor.swift
//  ConversationChat
//
//  Created by Raul Mantilla on 20/10/18.
//  Copyright (c) 2018 Raul Mantilla. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListContactsBusinessLogic
{
  func fetchContacts(request: ListContacts.FetchContacts.Request)
}

protocol ListContactsDataStore
{
  var contacts: [RealmContact] { get set }
  var selectedContact: ListContacts.FetchContacts.ViewModel.DisplayedContact? { get set }
}

class ListContactsInteractor: ListContactsBusinessLogic, ListContactsDataStore
{
  var presenter: ListContactsPresentationLogic?
  var worker: ListContactsWorker?
  var contacts: [RealmContact] = []
  var selectedContact: ListContacts.FetchContacts.ViewModel.DisplayedContact?
  
  // MARK: Do something
  
  func fetchContacts(request: ListContacts.FetchContacts.Request)
  {
    worker = ListContactsWorker()
    
    worker?.fetchContacts{ (contacts) in
        self.contacts = contacts
        let response = ListContacts.FetchContacts.Response(contacts: contacts)
        self.presenter?.presentContacts(response: response)
    }
  }
}
