//
//  ChatRoomsWorker.swift
//  ConversationChat
//
//  Created by Raul Mantilla on 14/10/18.
//  Copyright (c) 2018 Raul Mantilla. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

class ListChatRoomsWorker
{
    func fetchChatRooms(completionHandler completion: @escaping ([ChatRoom]) -> Void)
    {
        let realm = try! Realm()
        var chatRooms: [ChatRoom] = []
        
        let realmChatRooms = realm.objects(RealmChatRoom.self)
        for realmChatRoom in realmChatRooms {
            chatRooms.append(ChatRoom(withRealmChatRoom: realmChatRoom))
        }
        completion(chatRooms)
    }
}
