//
//  ListChatRoomsRouter.swift
//  ConversationChat
//
//  Created by Raul Mantilla on 14/10/18.
//  Copyright (c) 2018 Raul Mantilla. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListChatRoomsRoutingLogic
{
  func routeToConversation()
}

protocol ListChatRoomsDataPassing
{
  var dataStore: ListChatRoomsDataStore? { get }
}

class ListChatRoomsRouter: NSObject, ListChatRoomsRoutingLogic, ListChatRoomsDataPassing
{
  weak var viewController: ListChatRoomsViewController?
  var dataStore: ListChatRoomsDataStore?
  
    func routeToConversation()
    {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "ConversationRoomViewController") as! ConversationRoomViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToConversation(source: dataStore!, destination: &destinationDS)
        navigateToConversation(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToConversation(source: ListChatRoomsViewController, destination: ConversationRoomViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToConversation(source: ListChatRoomsDataStore, destination: inout ConversationRoomDataStore)
    {
        if let chatRoom = source.selectedChatRoom {
            destination.chatRoom = chatRoom
        }
    }
}
