//
//  ListChatRoomsPresenter.swift
//  ConversationChat
//
//  Created by Raul Mantilla on 14/10/18.
//  Copyright (c) 2018 Raul Mantilla. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListChatRoomsPresentationLogic
{
  func presentChatRooms(response: ListChatRooms.FetchChatRooms.Response)
}

class ListChatRoomsPresenter: ListChatRoomsPresentationLogic
{
  weak var viewController: ListChatRoomsDisplayLogic?
  
  // MARK: Present Chat Rooms
  
  func presentChatRooms(response: ListChatRooms.FetchChatRooms.Response)
  {
    var chatRooms: [ListChatRooms.FetchChatRooms.ViewModel.DisplayedChatRoom] = []
    for chatRoom in response.chatRooms
    {
        let displayedChatRooms = ListChatRooms.FetchChatRooms.ViewModel.DisplayedChatRoom(id: chatRoom.id, name: chatRoom.name, room_description: chatRoom.room_description, timestamp: chatRoom.timestamp, unreadMesagesCount: chatRoom.unreadMesagesCount, logoUrl: chatRoom.logoUrl, isPrivate: chatRoom.isPrivate, password: chatRoom.password)
        chatRooms.append(displayedChatRooms)
    }
    let viewModel = ListChatRooms.FetchChatRooms.ViewModel(displayedChatRooms: chatRooms)
    viewController?.displayChatRooms(viewModel: viewModel)
  }
}
